const collection = require('./connection');

const customerDb = [
    {
        "DatastorageID":"4J105-3-4",
        "PIID":"4J105-3-4",
        "Estimatedcoverage":10.2,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Illinois",
        "Collectionyear":null,
        "Improvementstatus":"Cultivar",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"5M20",
        "PIID":"5M20",
        "Estimatedcoverage":6.8,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":"Cultivar",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"AB-01",
        "PIID":"PI458020",
        "Estimatedcoverage":19.89950311,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"South Korea",
        "Origincity":"Seoul",
        "Collectionyear":1981.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"AB-02",
        "PIID":"PI603713",
        "Estimatedcoverage":27.94762804,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"sichuan",
        "Collectionyear":1998.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"BR-01",
        "PIID":"PI628809",
        "Estimatedcoverage":21.2240361,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Brazil",
        "Origincity":null,
        "Collectionyear":2001.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"BR-02",
        "PIID":"BRS 232",
        "Estimatedcoverage":12.82647168,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Brazil",
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"BR-03",
        "PIID":"PI675651",
        "Estimatedcoverage":17.81289437,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Brazil",
        "Origincity":null,
        "Collectionyear":2015.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"BR-04",
        "PIID":"BRS 360RR",
        "Estimatedcoverage":20.90837203,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Brazil",
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"BR-05",
        "PIID":"PI675666",
        "Estimatedcoverage":19.87212648,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Brazil",
        "Origincity":null,
        "Collectionyear":2015.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"BR-06",
        "PIID":"PI675660",
        "Estimatedcoverage":20.0718046,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Brazil",
        "Origincity":null,
        "Collectionyear":2016.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IX - MATURITY GROUP IX",
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"BR-07",
        "PIID":"BRS Valiosa RR",
        "Estimatedcoverage":16.23929934,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Brazil",
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"BR-08",
        "PIID":"BRSGO 8660",
        "Estimatedcoverage":14.49808353,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Brazil",
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"BR-09",
        "PIID":"BRSMG 850 GRR",
        "Estimatedcoverage":22.64127676,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Brazil",
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"BR-10",
        "PIID":"BRSMT Pintado",
        "Estimatedcoverage":19.91947411,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Brazil",
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"BR-11",
        "PIID":"CD 201",
        "Estimatedcoverage":23.08909214,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Brazil",
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"BR-12",
        "PIID":"PI663948",
        "Estimatedcoverage":21.46202866,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Brazil",
        "Origincity":null,
        "Collectionyear":2011.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"BR-13",
        "PIID":"PI628838",
        "Estimatedcoverage":19.20205194,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Brazil",
        "Origincity":null,
        "Collectionyear":2001.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"BR-14",
        "PIID":"PI628808",
        "Estimatedcoverage":23.21508448,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Brazil",
        "Origincity":null,
        "Collectionyear":2001.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"BR-15",
        "PIID":"IAC 8",
        "Estimatedcoverage":21.17284745,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Brazil",
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"BR-16",
        "PIID":"IAS 5",
        "Estimatedcoverage":15.66967766,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Brazil",
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"BR-17",
        "PIID":"MG\/BR46",
        "Estimatedcoverage":28.56654789,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Brazil",
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"BR-18",
        "PIID":"NA 5909 RG",
        "Estimatedcoverage":19.8179772,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Brazil",
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"BR-20",
        "PIID":"PI628879",
        "Estimatedcoverage":17.16329658,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Brazil",
        "Origincity":null,
        "Collectionyear":2001.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"BR-22",
        "PIID":"BR-22",
        "Estimatedcoverage":6.8,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"BR-23",
        "PIID":"PI628910",
        "Estimatedcoverage":11.75256988,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Brazil",
        "Origincity":null,
        "Collectionyear":2001.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"BR-24",
        "PIID":"PI628911",
        "Estimatedcoverage":10.1735573,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Brazil",
        "Origincity":null,
        "Collectionyear":2001.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"BR-29",
        "PIID":"BRSMT Uirapuru",
        "Estimatedcoverage":10.28519651,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Brazil",
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"BR-30",
        "PIID":"PI628925",
        "Estimatedcoverage":12.93085416,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Brazil",
        "Origincity":null,
        "Collectionyear":2001.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"BR-32",
        "PIID":"BRSGO Chapad\u00f5es",
        "Estimatedcoverage":12.85567848,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Brazil",
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2016)"
    },
    {
        "DatastorageID":"CL0J095",
        "PIID":"CL0J095",
        "Estimatedcoverage":8.2,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"CL0J173",
        "PIID":"CL0J173",
        "Estimatedcoverage":5.5,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"DT2000",
        "PIID":"PI635999",
        "Estimatedcoverage":17.33664155,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Vietnam",
        "Origincity":null,
        "Collectionyear":2004.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"ESS",
        "PIID":"PI548667",
        "Estimatedcoverage":46.75734291,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Virginia",
        "Collectionyear":1972.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"For",
        "PIID":"PI548645",
        "Estimatedcoverage":25.50959522,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Illinois",
        "Collectionyear":1989.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-DBK",
        "PIID":null,
        "Estimatedcoverage":15.27,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Korea",
        "Origincity":null,
        "Collectionyear":2001.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP001",
        "PIID":"S12-24185",
        "Estimatedcoverage":"G.max",
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":null,
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP002",
        "PIID":"S15-10570",
        "Estimatedcoverage":11.17,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":null,
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP003",
        "PIID":"S15-18319",
        "Estimatedcoverage":15.44,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":null,
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP004",
        "PIID":"S15-18613",
        "Estimatedcoverage":14.19,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":null,
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP005",
        "PIID":"E07158T",
        "Estimatedcoverage":13.99,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":null,
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP006",
        "PIID":"PI539860",
        "Estimatedcoverage":14.23,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Iowa",
        "Collectionyear":1990.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP007",
        "PIID":"PI556816",
        "Estimatedcoverage":18.2,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":null,
        "Collectionyear":1986.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP008",
        "PIID":"Jiyu 101",
        "Estimatedcoverage":14.38,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"China",
        "Origincity":"Jilin",
        "Collectionyear":null,
        "Improvementstatus":"Cultivar",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP009",
        "PIID":"R11-8397 ",
        "Estimatedcoverage":14.42,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP010",
        "PIID":"R12-5723",
        "Estimatedcoverage":13.67,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":null,
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP011",
        "PIID":"N17-1504",
        "Estimatedcoverage":15.24,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":null,
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP012",
        "PIID":"N17-1511",
        "Estimatedcoverage":13.59,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":null,
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP013",
        "PIID":"N17-1512",
        "Estimatedcoverage":16.18,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":null,
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP014",
        "PIID":"N17-1547",
        "Estimatedcoverage":17.02,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":null,
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP015",
        "PIID":"N17-1568",
        "Estimatedcoverage":19.58,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":null,
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP016",
        "PIID":"N17-1629",
        "Estimatedcoverage":19.37,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":null,
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP017",
        "PIID":"N17-1632",
        "Estimatedcoverage":18.08,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":null,
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP018",
        "PIID":"N17-1672",
        "Estimatedcoverage":14.31,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":null,
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP019",
        "PIID":"N17-1680",
        "Estimatedcoverage":18.03,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":null,
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP020",
        "PIID":"R05-638",
        "Estimatedcoverage":16.06,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":null,
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP021",
        "PIID":"R05-1415",
        "Estimatedcoverage":16.51,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Arkansas",
        "Collectionyear":2010.0,
        "Improvementstatus":"Breeding material",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP023",
        "PIID":"PI86490",
        "Estimatedcoverage":15.45,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Japan",
        "Origincity":"Akita",
        "Collectionyear":1930.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP024",
        "PIID":"PI96983",
        "Estimatedcoverage":16.76,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Korea",
        "Origincity":"North Korea",
        "Collectionyear":1932.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP025",
        "PIID":"PI163453",
        "Estimatedcoverage":17.26,
        "Species":"G.soja",
        "Ecotype":"Wild-type",
        "Origincountry":"China",
        "Origincity":"zhejiang",
        "Collectionyear":1948.0,
        "Improvementstatus":"Wild material",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP026",
        "PIID":"PI561288",
        "Estimatedcoverage":17.03,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Taiwan",
        "Origincity":null,
        "Collectionyear":1992.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP027",
        "PIID":"PI507449",
        "Estimatedcoverage":18.03,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Japan",
        "Origincity":"Kanto",
        "Collectionyear":1987.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP028",
        "PIID":"PI561292B",
        "Estimatedcoverage":16.83,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Taiwan",
        "Origincity":null,
        "Collectionyear":1992.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP029",
        "PIID":"PI536547B",
        "Estimatedcoverage":19.19,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Taiwan",
        "Origincity":null,
        "Collectionyear":1989.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP030",
        "PIID":"VG-001",
        "Estimatedcoverage":19.35,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":null,
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP031",
        "PIID":"PI643146",
        "Estimatedcoverage":17.67,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Ohio",
        "Collectionyear":2008.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP032",
        "PIID":"PI548983",
        "Estimatedcoverage":17.74,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Mississippi",
        "Collectionyear":1991.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP033",
        "PIID":"PI548654",
        "Estimatedcoverage":16.79,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Mississippi",
        "Collectionyear":1959.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP034",
        "PIID":"N17-1694",
        "Estimatedcoverage":19.16,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":null,
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP035",
        "PIID":"HR09-008",
        "Estimatedcoverage":15.04,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"North Carolina",
        "Collectionyear":2016.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP036",
        "PIID":"HR09-397",
        "Estimatedcoverage":16.94,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Ohio",
        "Collectionyear":null,
        "Improvementstatus":"Breeding material",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP037",
        "PIID":"HR10-2-559",
        "Estimatedcoverage":16.18,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":null,
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP038",
        "PIID":"PI676304",
        "Estimatedcoverage":16.11,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Ohio",
        "Collectionyear":2016.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":"II - MATURITY GROUP II",
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP039",
        "PIID":"PI567679-B",
        "Estimatedcoverage":16.05,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"henan",
        "Collectionyear":1993.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP040",
        "PIID":"PI555398",
        "Estimatedcoverage":16.11,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Maryland",
        "Collectionyear":1991.0,
        "Improvementstatus":"Breeding material",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP041",
        "PIID":"PI555399",
        "Estimatedcoverage":16.42,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Maryland",
        "Collectionyear":1991.0,
        "Improvementstatus":"Breeding material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP056",
        "PIID":"R09-430",
        "Estimatedcoverage":15.16,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Arkansas",
        "Collectionyear":2017.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP057",
        "PIID":"R13-359",
        "Estimatedcoverage":18.85,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Arkansas",
        "Collectionyear":null,
        "Improvementstatus":"Cultivar",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP058",
        "PIID":"R13-532",
        "Estimatedcoverage":14.47,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Arkansas",
        "Collectionyear":null,
        "Improvementstatus":"Cultivar",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP059",
        "PIID":"R95-1705",
        "Estimatedcoverage":13.41,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Arkansas",
        "Collectionyear":1995.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP060",
        "PIID":"UA-5615C",
        "Estimatedcoverage":15.26,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Arkansas",
        "Collectionyear":2015.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-HP061",
        "PIID":"UA-5814HP",
        "Estimatedcoverage":18.89,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Arkansas",
        "Collectionyear":2014.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-LD07",
        "PIID":"LD07-3419",
        "Estimatedcoverage":15.1,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Illinois",
        "Collectionyear":2012.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-PR052",
        "PIID":"PI423949",
        "Estimatedcoverage":16.41,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Japan",
        "Origincity":"Kumamoto",
        "Collectionyear":1976.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"I - MATURITY GROUP I",
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-PR053",
        "PIID":"PI372412",
        "Estimatedcoverage":20.08,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Romania",
        "Origincity":null,
        "Collectionyear":1972.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"000 - MATURITY GROUP 000",
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-PR054",
        "PIID":"PI437398",
        "Estimatedcoverage":16.29,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Russia",
        "Origincity":"Primorye",
        "Collectionyear":1979.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"I - MATURITY GROUP I",
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-PR055",
        "PIID":"PI398612",
        "Estimatedcoverage":17.31,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Korea",
        "Origincity":"Chungcheongbuk-do",
        "Collectionyear":1972.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-SU042",
        "PIID":"CR13-396",
        "Estimatedcoverage":17,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":null,
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-SU043",
        "PIID":"KB10-22#1608 0",
        "Estimatedcoverage":17.39,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":null,
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-SU044",
        "PIID":"R07-2001",
        "Estimatedcoverage":16.01,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Arkansas",
        "Collectionyear":null,
        "Improvementstatus":null,
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-SU045",
        "PIID":"PI417491",
        "Estimatedcoverage":15.69,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Japan",
        "Origincity":"Tohuku",
        "Collectionyear":1974.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-SU046",
        "PIID":"PI507336",
        "Estimatedcoverage":15.18,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Japan",
        "Origincity":"Ibaraka",
        "Collectionyear":1986.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-SU047",
        "PIID":"PI506903",
        "Estimatedcoverage":16.23,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Japan",
        "Origincity":"Tohuku",
        "Collectionyear":1987.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-SU048",
        "PIID":"PI416888",
        "Estimatedcoverage":16.99,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Japan",
        "Origincity":"Kanagawa",
        "Collectionyear":1974.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-SU049",
        "PIID":"PI506801B",
        "Estimatedcoverage":14.99,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Japan",
        "Origincity":"Ibaraka",
        "Collectionyear":1987.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-SU050",
        "PIID":"PI506799",
        "Estimatedcoverage":15.73,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Japan",
        "Origincity":"Ibaraka",
        "Collectionyear":1987.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN-SU051",
        "PIID":"PI506800B",
        "Estimatedcoverage":16.66,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Japan",
        "Origincity":"Ibaraka",
        "Collectionyear":1987.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"This study"
    },
    {
        "DatastorageID":"HN001",
        "PIID":"PI518664",
        "Estimatedcoverage":16.29545284,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Virginia",
        "Collectionyear":1988.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN002",
        "PIID":"PI548402",
        "Estimatedcoverage":17.36203374,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"China",
        "Origincity":"beijing",
        "Collectionyear":1954.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN003",
        "PIID":"PI89772",
        "Estimatedcoverage":18.15871975,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":null,
        "Collectionyear":1930.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN004",
        "PIID":"PI90763",
        "Estimatedcoverage":16.0718472,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"beijing",
        "Collectionyear":1930.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN005",
        "PIID":"PI404166",
        "Estimatedcoverage":18.36743942,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":null,
        "Collectionyear":1975.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN006",
        "PIID":"PI407788A",
        "Estimatedcoverage":17.01925456,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Korea",
        "Origincity":"Kyonggi",
        "Collectionyear":1975.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN007",
        "PIID":"PI424298",
        "Estimatedcoverage":17.92304855,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Korea",
        "Origincity":"Chungcheongbuk-do",
        "Collectionyear":1978.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN008",
        "PIID":"PI437655",
        "Estimatedcoverage":15.16256596,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":null,
        "Collectionyear":1979.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN009",
        "PIID":"PI495017C",
        "Estimatedcoverage":17.34988801,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"beijing",
        "Collectionyear":1985.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN010",
        "PIID":"PI468915",
        "Estimatedcoverage":13.76307798,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"Liaoning",
        "Collectionyear":1982.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"II - MATURITY GROUP II",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN011",
        "PIID":"PI507354",
        "Estimatedcoverage":14.7910163,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Japan",
        "Origincity":"Hokkaido",
        "Collectionyear":1987.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"I - MATURITY GROUP I",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN012",
        "PIID":"PI567305",
        "Estimatedcoverage":14.76623116,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"gansu",
        "Collectionyear":1993.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN013",
        "PIID":"S05-11482",
        "Estimatedcoverage":17.38915424,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":"Cultivar",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN015",
        "PIID":"PI437654",
        "Estimatedcoverage":17.87071226,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":null,
        "Collectionyear":1980.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN016B",
        "PIID":"PI567387",
        "Estimatedcoverage":13.48590133,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"shanxi",
        "Collectionyear":1993.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN017B",
        "PIID":"PI437725",
        "Estimatedcoverage":13.56198777,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":null,
        "Collectionyear":1980.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN018",
        "PIID":"PI437690",
        "Estimatedcoverage":15.96145167,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":null,
        "Collectionyear":1980.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN019",
        "PIID":"PI548402-2",
        "Estimatedcoverage":18.07502019,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"China",
        "Origincity":"beijing",
        "Collectionyear":1954.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN020",
        "PIID":"PI88788",
        "Estimatedcoverage":9.4,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"Liaoning",
        "Collectionyear":1930.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN021",
        "PIID":"PI209332",
        "Estimatedcoverage":17.39061265,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Japan",
        "Origincity":"Hokkaido",
        "Collectionyear":1953.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN022",
        "PIID":"PI404198B",
        "Estimatedcoverage":16.48454858,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":null,
        "Collectionyear":1975.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN023",
        "PIID":"PI424608A",
        "Estimatedcoverage":13.88644307,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Korea",
        "Origincity":"Kyongsang Puk",
        "Collectionyear":1978.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN024",
        "PIID":"PI548316",
        "Estimatedcoverage":19.42505323,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"China",
        "Origincity":"zhejiang",
        "Collectionyear":1947.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN025",
        "PIID":"PI567516C",
        "Estimatedcoverage":14.77743838,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"Shandong",
        "Collectionyear":1993.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN026",
        "PIID":"PI612611",
        "Estimatedcoverage":16.58481944,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Korea",
        "Origincity":"North",
        "Collectionyear":1998.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN027",
        "PIID":"S10-11227",
        "Estimatedcoverage":18.55395284,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":"Cultivar",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN028",
        "PIID":"PI572239",
        "Estimatedcoverage":13.4629117,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"North Carolina",
        "Collectionyear":1993.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN029",
        "PIID":"IA3023",
        "Estimatedcoverage":13.526358,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":null,
        "Collectionyear":null,
        "Improvementstatus":"Cultivar",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN030",
        "PIID":"PI598124",
        "Estimatedcoverage":13.5256215,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Missouri",
        "Collectionyear":1997.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN031",
        "PIID":"PI79691-4",
        "Estimatedcoverage":13.53607639,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"Heilongjiang",
        "Collectionyear":1929.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN032",
        "PIID":"PI86006",
        "Estimatedcoverage":13.52639086,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Japan",
        "Origincity":"Hokkaido",
        "Collectionyear":1930.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN033",
        "PIID":"PI87617",
        "Estimatedcoverage":13.54477249,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Korea",
        "Origincity":"Hamkysongpukto",
        "Collectionyear":1930.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN034",
        "PIID":"PI87631-1",
        "Estimatedcoverage":13.45887309,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Japan",
        "Origincity":"Saitama",
        "Collectionyear":1930.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN035",
        "PIID":"PI196175",
        "Estimatedcoverage":13.5365835,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Korea",
        "Origincity":"South",
        "Collectionyear":1947.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN036",
        "PIID":"PI200471",
        "Estimatedcoverage":14.29436294,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Japan",
        "Origincity":"Shikoku",
        "Collectionyear":1952.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN037",
        "PIID":"PI200508",
        "Estimatedcoverage":13.36708935,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Japan",
        "Origincity":"Shikoku",
        "Collectionyear":1952.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"I - MATURITY GROUP I",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN038",
        "PIID":"PI248515",
        "Estimatedcoverage":13.54941204,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Japan",
        "Origincity":"Honshu",
        "Collectionyear":1958.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN039",
        "PIID":"PI366121",
        "Estimatedcoverage":13.53485934,
        "Species":"G.soja",
        "Ecotype":"Wild-type",
        "Origincountry":"Japan",
        "Origincity":"Aizutakada",
        "Collectionyear":1971.0,
        "Improvementstatus":"Wild-material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN040",
        "PIID":"PI378702",
        "Estimatedcoverage":13.48456816,
        "Species":"G.soja",
        "Ecotype":"Wild-type",
        "Origincountry":"Japan",
        "Origincity":"Iwate",
        "Collectionyear":1973.0,
        "Improvementstatus":"Wild-material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN041",
        "PIID":"PI398593",
        "Estimatedcoverage":13.28182807,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Korea",
        "Origincity":"Chungcheongbuk-do",
        "Collectionyear":1974.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN042",
        "PIID":"PI398595",
        "Estimatedcoverage":13.34014107,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Korea",
        "Origincity":"Chungcheongbuk-do",
        "Collectionyear":1974.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN043",
        "PIID":"PI398610",
        "Estimatedcoverage":13.3199482,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Korea",
        "Origincity":"Chungcheongbuk-do",
        "Collectionyear":1974.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN044",
        "PIID":"PI398614",
        "Estimatedcoverage":13.27820774,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Korea",
        "Origincity":"Chungcheongbuk-do",
        "Collectionyear":1974.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN045",
        "PIID":"PI407162",
        "Estimatedcoverage":13.49654967,
        "Species":"G.soja",
        "Ecotype":"Wild-type",
        "Origincountry":"Korea",
        "Origincity":"Kyonggi",
        "Collectionyear":1972.0,
        "Improvementstatus":"Wild-material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN046",
        "PIID":"PI407184",
        "Estimatedcoverage":13.5334974,
        "Species":"G.soja",
        "Ecotype":"Wild-type",
        "Origincountry":"Korea",
        "Origincity":"Hwaseong Gun",
        "Collectionyear":1972.0,
        "Improvementstatus":"Wild-material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN047",
        "PIID":"PI407729",
        "Estimatedcoverage":13.52443809,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"beijing",
        "Collectionyear":1974.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN048",
        "PIID":"PI407965",
        "Estimatedcoverage":13.5571844,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Korea",
        "Origincity":"Cholla Nam",
        "Collectionyear":1975.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN049",
        "PIID":"PI408105A",
        "Estimatedcoverage":13.30329817,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Korea",
        "Origincity":"Kyongsang Puk",
        "Collectionyear":1975.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN050",
        "PIID":"PI416937",
        "Estimatedcoverage":15.28483121,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Japan",
        "Origincity":"Kanto",
        "Collectionyear":1974.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN051",
        "PIID":"PI424078",
        "Estimatedcoverage":13.56088655,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Korea",
        "Origincity":"Kangwon",
        "Collectionyear":1976.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN052",
        "PIID":"PI424079",
        "Estimatedcoverage":13.5191315,
        "Species":"G.soja",
        "Ecotype":"Wild-type",
        "Origincountry":"Korea",
        "Origincity":"Jung-sun Gun",
        "Collectionyear":1974.0,
        "Improvementstatus":"Wild-material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN053",
        "PIID":"PI424088",
        "Estimatedcoverage":13.76042825,
        "Species":"G.soja",
        "Ecotype":"Wild-type",
        "Origincountry":"Korea",
        "Origincity":"Je-chun Gun",
        "Collectionyear":1976.0,
        "Improvementstatus":"Wild-material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN054",
        "PIID":"PI437169B",
        "Estimatedcoverage":15.09944891,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Russia",
        "Origincity":"Krasnodar",
        "Collectionyear":1979.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"II - MATURITY GROUP II",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN055",
        "PIID":"PI437679",
        "Estimatedcoverage":13.29560701,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":null,
        "Collectionyear":1979.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN056",
        "PIID":"PI437863A",
        "Estimatedcoverage":13.52370087,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"Northeast",
        "Collectionyear":1979.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"II - MATURITY GROUP II",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN057",
        "PIID":"PI438258",
        "Estimatedcoverage":13.56855188,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"Northeast",
        "Collectionyear":1979.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"II - MATURITY GROUP II",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN058",
        "PIID":"PI458515",
        "Estimatedcoverage":13.66846871,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"Shandong",
        "Collectionyear":1981.0,
        "Improvementstatus":"Landrace",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN059",
        "PIID":"PI464920B",
        "Estimatedcoverage":13.70525527,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"Liaoning",
        "Collectionyear":1982.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN060",
        "PIID":"PI467312",
        "Estimatedcoverage":13.53196512,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"Jilin",
        "Collectionyear":1982.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"II - MATURITY GROUP II",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN061",
        "PIID":"PI471938",
        "Estimatedcoverage":13.50767866,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Nepal",
        "Origincity":null,
        "Collectionyear":1982.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN062",
        "PIID":"PI475783B",
        "Estimatedcoverage":13.44911274,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":null,
        "Collectionyear":1982.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN063",
        "PIID":"PI483463",
        "Estimatedcoverage":13.40353802,
        "Species":"G.soja",
        "Ecotype":"Wild-type",
        "Origincountry":"China",
        "Origincity":"shanxi",
        "Collectionyear":1984.0,
        "Improvementstatus":"Wild-material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN064",
        "PIID":"PI518751",
        "Estimatedcoverage":13.64161014,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Former Serbia",
        "Origincity":null,
        "Collectionyear":1988.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"II - MATURITY GROUP II",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN065",
        "PIID":"PI542044",
        "Estimatedcoverage":15.47757697,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Illinois",
        "Collectionyear":1990.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN066",
        "PIID":"PI547862",
        "Estimatedcoverage":13.49302018,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Illinois",
        "Collectionyear":1989.0,
        "Improvementstatus":"Genetic material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN067",
        "PIID":"PI548317",
        "Estimatedcoverage":15.98068036,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"China",
        "Origincity":"Hebei",
        "Collectionyear":1954.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN068",
        "PIID":"PI548349",
        "Estimatedcoverage":13.49554071,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"Korea",
        "Origincity":"Phyeongyang",
        "Collectionyear":1927.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN069",
        "PIID":"PI548415",
        "Estimatedcoverage":13.41655492,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"China",
        "Origincity":"zhejiang",
        "Collectionyear":1907.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN070",
        "PIID":"PI548511",
        "Estimatedcoverage":13.43858356,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Indiana",
        "Collectionyear":1978.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":"II - MATURITY GROUP II",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN071",
        "PIID":"PI548657",
        "Estimatedcoverage":13.70252156,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"North Carolina",
        "Collectionyear":1953.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN072",
        "PIID":"PI549031",
        "Estimatedcoverage":13.709432,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"beijing",
        "Collectionyear":1990.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN073",
        "PIID":"PI552538",
        "Estimatedcoverage":13.72794883,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Nebraska",
        "Collectionyear":1991.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN074",
        "PIID":"PI561271",
        "Estimatedcoverage":13.46480486,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"zhejiang",
        "Collectionyear":1992.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN075",
        "PIID":"PI567230",
        "Estimatedcoverage":13.82724527,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"shanxi",
        "Collectionyear":1993.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN076",
        "PIID":"PI567336B",
        "Estimatedcoverage":13.78813662,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"gansu",
        "Collectionyear":1993.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN077",
        "PIID":"PI567343",
        "Estimatedcoverage":13.795604,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"gansu",
        "Collectionyear":1993.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN078",
        "PIID":"PI567354",
        "Estimatedcoverage":13.83377633,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"gansu",
        "Collectionyear":1993.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN079",
        "PIID":"PI567357",
        "Estimatedcoverage":13.77943339,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"Ningxia",
        "Collectionyear":1993.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN080",
        "PIID":"PI567383",
        "Estimatedcoverage":13.81040381,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"shanxi",
        "Collectionyear":1993.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN081",
        "PIID":"PI567519",
        "Estimatedcoverage":13.57979393,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"Shandong",
        "Collectionyear":1993.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN082",
        "PIID":"PI567611",
        "Estimatedcoverage":13.55999138,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"henan",
        "Collectionyear":1993.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN083",
        "PIID":"PI567651",
        "Estimatedcoverage":13.53323369,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"henan",
        "Collectionyear":1993.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN084",
        "PIID":"PI567690",
        "Estimatedcoverage":13.57584889,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"anhui",
        "Collectionyear":1993.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN085",
        "PIID":"PI567719",
        "Estimatedcoverage":13.59366887,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"anhui",
        "Collectionyear":1993.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN086",
        "PIID":"PI567731",
        "Estimatedcoverage":13.57419013,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"anhui",
        "Collectionyear":1993.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN087",
        "PIID":"PI591539",
        "Estimatedcoverage":13.48104145,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Illinois",
        "Collectionyear":1995.0,
        "Improvementstatus":"Genetic material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN088",
        "PIID":"PI593258",
        "Estimatedcoverage":13.58952608,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Illinois",
        "Collectionyear":1996.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN089",
        "PIID":"PI594012",
        "Estimatedcoverage":13.55258973,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Korea",
        "Origincity":"South",
        "Collectionyear":1995.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN090",
        "PIID":"PI594512A",
        "Estimatedcoverage":15.99788439,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"sichuan",
        "Collectionyear":1996.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN091",
        "PIID":"PI594599",
        "Estimatedcoverage":13.54759149,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"hunan",
        "Collectionyear":1996.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN092",
        "PIID":"PI597387",
        "Estimatedcoverage":13.52223086,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Illinois",
        "Collectionyear":1997.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN093",
        "PIID":"PI603154",
        "Estimatedcoverage":13.63842553,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Korea",
        "Origincity":"North Korea",
        "Collectionyear":1997.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN094",
        "PIID":"PI603170",
        "Estimatedcoverage":13.56530682,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Korea",
        "Origincity":"North Korea",
        "Collectionyear":1997.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN095",
        "PIID":"PI603175",
        "Estimatedcoverage":16.18226597,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Korea",
        "Origincity":"North",
        "Collectionyear":1997.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN096",
        "PIID":"PI603176A",
        "Estimatedcoverage":13.616171,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Korea",
        "Origincity":"North Korea",
        "Collectionyear":1997.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN097",
        "PIID":"PI603497",
        "Estimatedcoverage":13.55978768,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"China",
        "Origincity":"Shandong",
        "Collectionyear":1998.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"III - MATURITY GROUP III",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN098",
        "PIID":"PI605869A",
        "Estimatedcoverage":13.40659474,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Vietnam",
        "Origincity":"laocai",
        "Collectionyear":1998.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN099",
        "PIID":"PI639740",
        "Estimatedcoverage":13.7265469,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Illinois",
        "Collectionyear":2005.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":"IV - MATURITY GROUP IV",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN100",
        "PIID":"PI647086",
        "Estimatedcoverage":13.625321,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"North Carolina",
        "Collectionyear":2007.0,
        "Improvementstatus":"Cultivar",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN101",
        "PIID":"PI658519",
        "Estimatedcoverage":13.60589579,
        "Species":"G.max",
        "Ecotype":"Cultivar",
        "Origincountry":"USA",
        "Origincity":"Illinois",
        "Collectionyear":2009.0,
        "Improvementstatus":"Breeding material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN104",
        "PIID":"FC31721",
        "Estimatedcoverage":14.91580846,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Unknown",
        "Origincity":null,
        "Collectionyear":1947.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":null,
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN105",
        "PIID":"PI438471",
        "Estimatedcoverage":14.94452145,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Sweden",
        "Origincity":"\u00d6sterg\u00f6tlands l\u00e4n",
        "Collectionyear":null,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"00 - MATURITY GROUP 00",
        "Dataresource":"(Valliyodan et al., 2021)"
    },
    {
        "DatastorageID":"HN106",
        "PIID":"PI417091",
        "Estimatedcoverage":15.40992507,
        "Species":"G.max",
        "Ecotype":"Landrace",
        "Origincountry":"Japan",
        "Origincity":"Kanto",
        "Collectionyear":1974.0,
        "Improvementstatus":"Cultivated material",
        "Maturity_group":"II - MATURITY GROUP II",
        "Dataresource":"(Valliyodan et al., 2021)"
    }
]


module.exports = async () => {
    try {
        let customerModel = await collection.getCustomerCollection();
        let insertedCustomers = await customerModel.insertMany(customerDb);
      
        if (insertedCustomers.length) {
            return { message: "Database Initialized" }
        } else {
            // let err = new Error("Database Initialization failed");
            // err.status = 400;
            // throw err;
            console.log("failed else setup")
        }
    } catch (error) {
        // let err = new Error("Database Initialization failed");
        // err.status = 400;
        // throw err;
        console.log("in catch setup")
    }
}